import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/*
module.exports = {
  someSidebar: {
    Guide: [
      'guide/getting-started',
      'guide/custom-component',
      'guide/migrating',
      'guide/faq',
    ],
    API: ['api/mui', 'api/mui-x-date-pickers'],
  },
};
*/

const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  someSidebar: {
    Guide: [
      'guide/getting-started',
      'guide/custom-component',
      'guide/migrating',
      'guide/faq',
    ],
    API: ['api/mui', 'api/mui-x-date-pickers'],
  },
};

export default sidebars;